#nelmio_cors:
#   defaults:
#       origin_regex: true
#       allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#       allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#       allow_headers: ['Content-Type', 'Authorization']
#       expose_headers: ['Link']
#       max_age: 3600
#   paths:
#       '^/': null


nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['http://localhost:5173']  # Votre frontend
    allow_headers: ['Content-Type', 'Authorization', 'X-User-Id']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    expose_headers: []
    max_age: 3600
  paths:
    '^/api/':  # Appliquer cette configuration à toutes les routes commençant par /api
      allow_origin: ['http://localhost:5173']
      allow_headers: ['Content-Type', 'Authorization', 'X-User-Id']
      allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]

